aws/aws-parallelcluster-ui

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Storage.tsx
- frontend/src/old-pages/Configure/Storage/__tests__/validateStorageName.test.ts
- frontend/src/old-pages/Configure/Storage/storage.validators.ts
Add the ability to override the name of a shared storage.
> Let the user specify a custom name for the shared storage

- .github/workflows/production_release.yml
- infrastructure/parallelcluster-ui.yaml
- scripts/README.md
- scripts/build_and_release_image.sh
This PR removes the need to specify a REVISION separately and expects a new format for the (now mandatory) `--tag` parameter, which used to be optional.
It is now mandatory because the default tagging strategy is considered dangerous and is now removed with this PR.
- `production_release.yaml` action
- `build_and_release_image.sh` script
- `scripts/README.md` updated with current usage
- manually on a different branch with custom triggers and test code
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …
> Handle revision in --tag parameter for prod release script + remove default strategy for tagging

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Storage.tsx
- frontend/src/old-pages/Configure/Storage.types.ts
- frontend/src/old-pages/Configure/Storage/AddStorageForm.tsx
- frontend/src/old-pages/Configure/Storage/__tests__/AddStorageForm.test.tsx
- frontend/src/old-pages/Configure/Storage/__tests__/buildStorageEntries.test.ts
- frontend/src/old-pages/Configure/Storage/__tests__/mapStorageToUiSettings.test.ts
- frontend/src/old-pages/Configure/Storage/buildStorageEntries.ts
- frontend/src/old-pages/Configure/Storage/storage.mapper.ts
This PR adds the possibility to add more than one storage at a time.
In addition, it updates the UI, by showing each Storage instance in its own container
- fix typo in storage types
- use `Alert` for the empty state
- move storage instances list below the add storage form
- add `AddStorageForm` and `buildStorageEntries` to support selection of multiple storage types
**New empty state**
**Multiselect**
**Updated UI for Storage instances list**
- manually
- created storages, in Create mode
- edited existing storages, in Edit mode
- unit tests
By submitting this pull request, I …
> Add possibility to select more than one storage at a time

- infrastructure/parallelcluster-ui.yaml
Previously the `EcrImageDeletionLambda` wasn't able to delete all images in the private ecr repository because an `if` condition inside a list comprehension didn't include all images, so only a subset (possibly empty) of the images id were targetet.
Now, all images get deleted, and the CloudFormation resource (ECR private repo) can be safely removed.
This PR fixes #33 
- manually
> Fixed broken 'delete stack' due to EcrPrivateRepository being not empty

- e2e/specs/wizard.spec.ts
- e2e/specs/wizard.template.spec.ts
Fixes failing e2e tests https://github.com/aws/aws-parallelcluster-ui/actions/runs/4264550625.
- Run e2e tests locally
> Fix e2e tests after moving Queues before Storage

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/HeadNode.tsx
- frontend/src/old-pages/Configure/Queues/Queues.tsx
- frontend/src/old-pages/Configure/Queues/SlurmMemorySettings.tsx
- frontend/src/old-pages/Configure/SlurmSettings/SlurmSettings.tsx
- fixes an issue with the Head node page validation
- moved the Slurm  properties under the Queues section
The produced config has also the selected parameters with the right values
> Move QueueUpdateStrategy and DownIdleTime time under Queues -> Slurm settings

- frontend/locales/en/strings.json
- frontend/src/feature-flags/__tests__/FeatureFlagsProvider.test.ts
- frontend/src/feature-flags/featureFlagsProvider.ts
- frontend/src/feature-flags/types.ts
- frontend/src/old-pages/Configure/Storage.tsx
- frontend/src/old-pages/Configure/Storage.types.ts
- frontend/src/old-pages/Configure/Storage/DeletionPolicyFormField.tsx
- frontend/src/old-pages/Configure/Storage/__tests__/DeletionPolicyFormField.test.tsx
- frontend/src/old-pages/Configure/__tests__/storage.test.tsx
This PR adds support for the `DeletionPolicy` configuration for Efs and FsxLustre storage types.
- add `DeletionPolicyFormField`
- only show the field for versions that support the `DeletionPolicy` (Ebs: 3.2.0, Efs and FsxLustre: 3.3.0)
- support `Delete` and `Retain` for Efs and FsxLustre, support also `Snapshot` for Ebs
- default to `Retain` for every storage type
- add tests to the single storage instance
- manually, by adding all storage types and running the dry run
- manually, by changing PC version and making sure nothing is displayed
- unit/integration tests
**FsxLustre**
**Efs**
**Ebs**
Closes #70 
In order to increase the likelihood of your contribution being accepted, please make sure you have read both the [Contributing Guidelines](../CONTRIBUTING.md) and the [Project …
> Add support for DeletionPolicy for Efs and FsxLustre

- frontend/src/old-pages/Configure/Cluster.tsx
- frontend/src/old-pages/Configure/Cluster/OsFormField.tsx
- frontend/src/old-pages/Configure/Cluster/__tests__/OsFormField.test.tsx
This PR adopts the [Tiles](https://cloudscape.design/components/tiles/?tabId=api) component to let users select the Operating System
- replace `Select` with `Tiles`
- add test
- manually
- unit test
- [Tiles](https://cloudscape.design/components/tiles/?tabId=api)
> Use Tiles to select Operating System

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Queues/Queues.test.tsx
- frontend/src/old-pages/Configure/Queues/Queues.tsx
- frontend/src/old-pages/Configure/useWizardNavigation.ts
- increases queues limits to 10 and compute resources to 5
- fixes a bug introduced after #67 
Validated with a dry run after adding 10 queues and 5 compute resources on the first queue
> Increase queues limits

- frontend/src/old-pages/Configure/Cluster.tsx
- frontend/src/old-pages/Configure/HeadNode.tsx
- frontend/src/old-pages/Configure/SlurmSettings/SlurmAccountingForm.tsx
- frontend/src/old-pages/Configure/SlurmSettings/SlurmSettings.tsx
- frontend/src/old-pages/Configure/SlurmSettings/__tests__/SlurmSettings.test.tsx
- frontend/src/old-pages/Configure/Storage.tsx
This PR moves the Slurm Settings section from the HeadNode section to the Cluster section
- move `SlurmSettings` to the Cluster section (both component and validation)
- adjust spacing between Storage instances for consistency  
- fix `SlurmSettings` container rendering empty in older versions of PC
- manually, attempted a dry run
- added unit test
> Move Slurm accounting settings under Cluster page

- frontend/src/old-pages/Configure/Queues/MultiInstanceComputeResource.tsx
- frontend/src/old-pages/Configure/Queues/Queues.test.tsx
Since multi-threading is not enabled for HPC instances, the corresponding queues options are now disabled.
- Selected two instances for compute resources, one is a `hpc6a.48xlarge`
- "Turn off multithreading" is disabled and cannot be selected
- the setting is not present in the final config
> Disabled multithreading options when an hpc instance is selected

- frontend/src/old-pages/Clusters/Accounting.tsx
- frontend/src/old-pages/Clusters/Clusters.tsx
- frontend/src/old-pages/Clusters/Filesystems.tsx
- frontend/src/old-pages/Clusters/Instances.tsx
- frontend/src/old-pages/Clusters/Scheduling.tsx
- frontend/src/old-pages/Images/CustomImages/CustomImageDetails.tsx
- frontend/src/old-pages/Images/CustomImages/CustomImages.tsx
- frontend/src/old-pages/Images/OfficialImages/OfficialImages.tsx
- frontend/src/old-pages/Users/Users.tsx
- frontend/src/shared/__tests__/extendCollectionsOptions.test.ts
- frontend/src/shared/extendCollectionsOptions.ts
This PR adds a centralized mechanism to set defaults to the `useCollections` hook
- add mixin to extend the default useCollections options
- adopt defaults in every instance of `useCollections`, save Logs and StackEvents
- manually
- unit test
> Provide a reasonable default for table page size

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Cluster.tsx
- frontend/src/old-pages/Configure/Configure.tsx
- frontend/src/old-pages/Configure/Queues/MultiInstanceComputeResource.tsx
- frontend/src/old-pages/Configure/Queues/Queues.test.tsx
- frontend/src/old-pages/Configure/Queues/Queues.tsx
- frontend/src/old-pages/Configure/Queues/SingleInstanceComputeResource.tsx
- frontend/src/old-pages/Configure/Queues/__tests__/hasMultipleInstanceTypes.test.tsx
- frontend/src/old-pages/Configure/Queues/__tests__/validateQueueName.test.ts
- frontend/src/old-pages/Configure/Queues/queues.validators.tsx
This PR refactors the design of Queues wizard page. Now each queue has its own dedicated container, and compute resources are not wrapped in an additional container.
Furthemore:
* `Add queue` button has been moved to the top-right part of the container
* Compute resources names are now displayed in the wizard
* Added Queue name validation
* Manual tests on local environment
* Unit tests
* https://cloudscape.design/components/column-layout/
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> Refactor design of Queues wizard page

- infrastructure/parallelcluster-ui.yaml
This PR does two things:
- it improves the description of the subnet parameter specifying only public subnets are allowed
- it fixes a wrong grouping of CF parameters caused by some of them not being treated by the CF Interfaces
> Improved subnet parameter description + fixed parameters structure and groupings in main CF template

- frontend/src/components/ValueWithLabel.tsx
- frontend/src/old-pages/Clusters/Properties.tsx
Arrange cluster properties layout for a better alignment of the content displayed.
My initial idea was to leverage just the `ColumnLayout` and let Cloudscape arrange the properties, but, after reading the [key-value pairs guidelines](https://cloudscape.design/components/key-value-pairs/) I used the current layout and changed just the ordering of properties to make it coherent.
There will still be blanks in the layout, especially if the cluster is private, but there's no way to use the `variant=text-grid` with a random number of elements in `ColumnLayout`.
Created a cluster with a public IP to show all the available properties.
https://cloudscape.design/components/key-value-pairs/
In order to increase the likelihood of your contribution being accepted, please make sure you have read both …
> Arrange cluster properties layout

- frontend/src/components/HiddenFileUpload.tsx
- frontend/src/components/__tests__/HiddenFileUpload.test.tsx
- frontend/src/old-pages/Configure/Source.tsx
This PR improves the hidden file uploader so that it can be controlled via props. This is part of a bigger effort to change way the cluster creation can be started by the user.
Follow up PRs will be linked to this
- deprecate existing `HiddenUploader` so not to break the `Source` page with this PR
- refactor `HiddenFileUpload` to be controlled via props
- manually
- unit test
- a proper test checking that the `onChange` handler is being called after upload file is missing, this is due to the difficulty to simulate a file upload while also controlling the behaviour of the `onload` event of the `FileReader`
- this is partially mitigated by [existing e2e tests](https://github.com/aws/aws-parallelcluster-ui/blob/main/e2e/specs/wizard.template.spec.ts)
In order to increase the likelihood of …
> Allow HiddenFileUpload to be controlled via props

- e2e/specs/wizard.spec.ts
- e2e/specs/wizard.template.spec.ts
- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Cluster.tsx
- frontend/src/old-pages/Configure/Cluster/ClusterNameField.tsx
- frontend/src/old-pages/Configure/Cluster/__tests__/clusterName.validators.test.ts
- frontend/src/old-pages/Configure/Cluster/clusterName.validators.ts
- frontend/src/old-pages/Configure/Source.tsx
This PR moves the cluster name field from the Source section to the Cluster section
- add `ClusterNameField` and validators
- move cluster name field from `Source` to `Cluster`
- adjust e2e tests
- manually
- unit tests
- local e2e test
> Move cluster name field from Source to Cluster section

- e2e/specs/wizard.spec.ts
- e2e/specs/wizard.template.spec.ts
- frontend/src/old-pages/Clusters/Actions.tsx
- frontend/src/old-pages/Clusters/__tests__/Clusters.test.tsx
- frontend/src/old-pages/Configure/Cluster.tsx
- frontend/src/old-pages/Configure/Cluster/ClusterNameField.tsx
- frontend/src/old-pages/Configure/Cluster/__tests__/ClusterNameField.test.tsx
- frontend/src/old-pages/Configure/Configure.tsx
- frontend/src/old-pages/Configure/useWizardNavigation.ts
This PR adds a dropdown button to pick the source from which to create a cluster. It replaces the Source section of the wizard.
It builds upon the work done with #93
Closes #32 
**A follow up PR will remove the inactive code of the Source page**
- remove `source` from the steps of the wizard
- add dropdown button to `/clusters` page
- align e2e tests
- manually
- uploaded a template, checked that the final config matches with the uploaded one
- create from cluster, checked that the final config matches with the source cluster
- e2e tests
By submitting this pull request, I …
> Select method to create cluster via button dropdown

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/HeadNode.tsx
This PR literally moves the subnet id dropdown to a new container Networking according to our figma.
And also adds an Alert.
The Alert is not inside a Box since it apparently made no difference.
- manually 
- unit tests
> Moved subnet dropdown to a new "Networking" container

- api/validation/schemas.py
- api/validation/validators.py
This PR increases the maximum allowed payload size in calls towards PC.
This allows for bigger YAML configuration file
The limit has been set to 1MB, which respects the following:
- allows for huge configuration files
- respects [AWS Lambda payload limit](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html) (6 MB)
- respects [CloudFormation template size limit](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html) (1 MB)
- increase limit from 8kib to 1MB
- explicit unit of measurement in the error message
- manually, by importing a YAML file that previously had been rejected by the current limit (size ~9kb)
- discarded unit tests, since I ended up testing the library and our configuration, with the downsize of running 1MB of mocked …
> Increase maximum allowed payload size

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Components.tsx
Use Cloudscape Multiselect component to simplify the selection of security groups.
Fixes #38 
Validated setting 2 security groups on the head node and 1 on a queue, dry run passes
- [] I added tests to new or existing code
> Use a Multiselect for selecting security groups

- frontend/locales/en/strings.json
- frontend/src/css-properties.d.ts
- frontend/src/old-pages/Configure/Components.module.css
- frontend/src/old-pages/Configure/Components.tsx
- frontend/src/old-pages/Configure/__tests__/Components.test.tsx
Align the layout of the custom actions editor.
- add support for passing custom CSS variables
- add a CSS class to implement a SpaceBetween with horizontally aligned items
- actions editor layout changes
- Local dry run after filling custom actions
> Custom actions editor layout changes

- frontend/src/old-pages/Configure/Configure.tsx
- frontend/src/old-pages/Configure/HeadNode.tsx
- frontend/src/old-pages/Configure/__tests__/IMDSSecuredSettings.test.tsx
This PR changes the default for the "set IMDS secured" checkbox by saving the chosen value in a separate place and clearing it when the wizard need the be cleared.
- manually
- unit tests
> IMDS secured set as True by default for new cluster creation

- frontend/locales/en/strings.json
- frontend/src/old-pages/Clusters/Scheduling.tsx
Fixes #109.
Show as "Not available" the undefined job properties. I chose this approach to have a consistent layout for job properties, and highlight when a property does not exist.
Submitted a simple job to the head node and verified missing properties are shown as N/A
> Fix a crash happening when showing a job with undefined properties

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Components.tsx
- frontend/src/old-pages/Configure/Components.types.ts
- frontend/src/old-pages/Configure/Queues/MultiInstanceComputeResource.tsx
Currently instance type selection in Head node wizard page is implemented leveraging [Autosuggest](https://cloudscape.design/components/autosuggest/?tabId=playground) Cloudscape component.
This PR replaces the `Autosuggest` component with a `Select` component, in order to show instance metadata such as memory, virtual cores and Gpu info upon selection.
* Manually tests on local environment
* https://cloudscape.design/components/select/?tabId=playground
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …
> Show instance type metadata in dropdown selection in Head node wizard Page

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Components.tsx
- frontend/src/old-pages/Configure/HeadNode.tsx
Adapt head node storage to the new layout.
> Head node storage layout changes

- frontend/src/old-pages/Images/CustomImages/CustomImages.tsx
Delesect the selected custom image when htting the refresh button, mimicking the EC2 console behavior.
- Selected a custom image
- Hit refresh button
- The split panel is emptied and the list has no images selected
> Deselect custom image when hitting the refresh button

- frontend/src/old-pages/Clusters/Actions.tsx
Disable SSM-based actions only when the SSM policy is not applied.
The check on the head node public IP address is kept only for the DCV button.
- created two clusters, one with and one without the SSM policy
- I cannot click on the Shell and Filesystem button when SSM is disabled
- I can click on the Shell and Filesystem button when SSM is enabled
> Remove head node check from SSM-based actions

- frontend/src/old-pages/Configure/HeadNode.tsx
- frontend/src/old-pages/Configure/__tests__/IMDSSecuredSettings.test.tsx
When in editing mode, the IMDS secured must not be changed since it will break cluster update.
This PR solves that bug introduced by #101 
- manual
- unit tests
> Don't act on IMDS secured default settings when in update mode

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Create.tsx
- frontend/src/old-pages/Configure/Create.types.ts
- frontend/src/old-pages/Configure/__tests__/errorsToFlashbarItems.test.ts
Currently, upon a dry-run/creation of a cluster, we are showing errors through a custom `ValidationErrors` component, which displays errors in a styled `div`.
In order to be compliant with Cloudscape, we need to display errors leveraging `Flashbar` component, at the top YAML code editor.
This PR introduces Cloudscape `Flashbar` component in place of `ValidationErrors`.
* E2E tests
* Unit tests
* Manual tests
* Verified that `Flashbar` is displayed with success message (with and without validation warnings)
* Verified that `Flashbar` is displayed with error messages upon cluster creation
* Verified that `Flashbar` is displayed with error messages upon cluster editing
* https://cloudscape.design/components/flashbar
In order to increase the likelihood of your contribution being accepted, …
> Use Flashbar in place of ValidationErrors component

- e2e/specs/wizard.fromcluster.spec.ts
- e2e/specs/wizard.spec.ts
- e2e/specs/wizard.template.spec.ts
- e2e/test-utils/login.ts
- e2e/test-utils/wizard.ts
This PR adds an e2e spec to test the cluster creation wizard when starting from an existing cluster.
- add e2e test utils to fill in the wizard sections
- add spec for the "From cluster" scenario
- running the e2e locally
> Add e2e spec for creating a cluster from another cluster

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Components.tsx
- frontend/src/old-pages/Configure/HeadNode.tsx
* Added missing input fields placeholders
* Reduced advanced options spacing between elements
* Removed 'optional' from "IAM Policies" title
* Changed "Scripts" header from h5 to h3
* Manually verified on affected pages in local environment
> Apply UI minor fixes to HeadNode wizard page

- frontend/locales/en/strings.json
- frontend/src/old-pages/Clusters/StackEvents.tsx
- frontend/src/old-pages/Configure/Configure.tsx
* Remove refresh icon from refresh buttons
* Add missing i18n strings
* Manually inspected affected pages on local environment
> Remove refresh icon from refresh buttons

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/SlurmSettings/SlurmAccountingForm.tsx
- frontend/src/old-pages/Configure/SlurmSettings/SlurmSettings.tsx
* Moved Slurm settings under expandable section
* Added missing placeholders for Slurm settings fields
* Moved help panel info link into individual fields
* Manually inspected affected section in local environment
* https://cloudscape.design/components/expandable-section/?tabId=playground&example=container
> Move slurm settings under expandable section and add placeholder fields

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Storage.tsx
This PR introduces minor fixes for `Storage` wizard page:
* Added 'Storage settings' title container
* Addded and fix missing placeholders in input fields
* Manually inspected affected pages on local environment
* https://cloudscape.design/components/input/?tabId=playground
> Storage wizard page minor fixes

- frontend/src/old-pages/Clusters/Clusters.tsx
- frontend/src/old-pages/Images/CustomImages/CustomImages.tsx
- frontend/src/old-pages/Images/OfficialImages/OfficialImages.tsx
- frontend/src/old-pages/Logs/LogMessagesTable.tsx
- frontend/src/old-pages/Logs/LogStreamsTable.tsx
This PR updates table headers so to display the total number of entries
- update Cluster list counter
- update Official Images list counter
- update Custom Images list counter
- update LogStreams and LogMessages list counter
- manually, by simulating everything works fine when
- no data is returned at all (defaults to 0)
- data is returned (shows total count)
> Show count of total entries in table headers

- frontend/src/old-pages/Configure/Create.tsx
- frontend/src/old-pages/Configure/__tests__/errorsToFlashbarItems.test.ts
Currently upon cluster creation, outcome messages are stacked following the same order of the returned JSON from PC API, and errors comes at the very end, causing the UI to display a blue message instead of a red one.
This PR introduces a mechanism to sort Flashbar items according the following priority:
1. `success`
2. `error`
3. `warning`
4. `info`
* Unit tests
* Manually triggered different dry-runs
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
By submitting this pull request, I confirm that you can use, modify, copy, and …
> Sort create cluster outcome messages based on severity

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Cluster.tsx
- frontend/src/old-pages/Configure/Queues/MultiInstanceComputeResource.tsx
- frontend/src/old-pages/Configure/Queues/Queues.test.tsx
- frontend/src/old-pages/Configure/Queues/Queues.tsx
- frontend/src/old-pages/Configure/Queues/SingleInstanceComputeResource.tsx
- frontend/src/old-pages/Configure/Queues/SubnetMultiSelect.tsx
This PR introduces minor fixes for queues wizard page:
* Changed name structure for queues and compute resources
* Make add/remove button to be repeated in every queue
* Stack EFA/Multithreading checkboxes vertically
* Add missing placeholders for input fields
* Unit tests
* Manually inspected affected pages in local environment, targeting version of PC API 3.2.0 and 3.5.0
> Queues wizard page minor fixes

- frontend/src/old-pages/Logs/LogMessagesTable.tsx
This PR shows a `+` symbol next to the Log Messages count, with the following logic:
- when the count is 0, show `(0)`
- otherwise, show `(N+)`
This is done to be explicit about the fact that we don't know the total number of messages (as expressed in [CloudScape guidelines](https://cloudscape.design/components/table/?tabId=usage))
- manually, by checking both 0 and non-zero case
- [Counter guidelines](https://cloudscape.design/components/table/?tabId=usage)
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
> Add + symbol to log messages count

- decisions/20230327-disable-fetch-on-focus.md
Following this suggestion https://github.com/aws/aws-parallelcluster-ui/pull/126/commits/1e60ffaf2532b87353e283139b5d790622b1fd5d#r1141975407, this PR adds an ADR marking the decision to disable the fetch on focus feature of react-query
> Add ADR on disable fetch on focus

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Components.module.css
- frontend/src/old-pages/Configure/Components.tsx
- frontend/src/old-pages/Configure/HeadNode.tsx
- frontend/src/old-pages/Configure/Queues/MultiInstanceComputeResource.tsx
- frontend/src/old-pages/Configure/Queues/Queues.tsx
See commits tab
Compute resource before
Compute resource after
> Adjust the layout of some wizard components

- frontend/locales/en/strings.json
- frontend/src/old-pages/Clusters/Accounting.tsx
- frontend/src/old-pages/Clusters/Scheduling.tsx
This PR improves the empty states, by adding instructions on how to act on an empty list. 
In addition, it removes Sentence Casing where used, to comply with copywriting guidelines.
Refer to commit list
- manually, on the lists that have been changed
> Adopt empty state copy best practices

- frontend/src/old-pages/Configure/Storage.tsx
- frontend/src/old-pages/Configure/__tests__/storage.test.tsx
Fixes #116.
- added an FSx storage type
- switched the type to SCRATCH_1
- dry run passed
- went back to the storage to switch the type back to PERSISTENT_1
- PerUnitStorageThroughput is appended correctly and dry run passes
> Don't set PerUnitStorageThroughput on SCRATCH FSx

- frontend/.eslintignore
- frontend/.eslintrc.json
- frontend/jest.config.js
- frontend/src/components/ErrorBoundary.tsx
- frontend/src/components/__tests__/useLoadingState.test.tsx
- frontend/src/components/useLoadingState.tsx
- frontend/src/model.tsx
- frontend/src/pages/index.tsx
This PR introduces a preliminary "step" to the loading of the application, a loading state is shown when the application is first displayed and two set of info are downloaded, since they are necessary for the inner workings of the application.
- application config (with info like where to redirect an authenticating user, etc.)
- identity of the user (if the user is actually authenticated)
Important: this PR doesn't handle the same loading state with preliminary info download in case of a region change from the region selector!
- added new hook `useLoadingState`
- `GetIdentity` and `GetAppConfig` functions are now exported
- `GetIdentity` now always throws the error it gets since it is only used in one place (inside the `useLoadingState` hook)
- `GetIdentity` not returns the http response …
> Add a loading state spinner at application loading time to prevent portal usage before necessary info are downloaded

- e2e/configs/environment.ts
The `noMatch` tests are flaky because the Cognito redirection is pointing to the new URL without preserving the path.
- run e2e locally and verified the `noMatch` spec is working
> Point E2E to the new custom domain

- frontend/src/auth/types.ts
- frontend/src/components/__tests__/useLoadingState.test.tsx
- frontend/src/components/useLoadingState.tsx
- frontend/src/model.tsx
- frontend/src/pages/index.tsx
- frontend/src/store.ts
This PR fixes an issue with the loading state inadvertently showing error messages while loading the data
- only fire `useLoadingState` when the needed data is missing
- make sure loader is not removed in case of an authn/z error (which is handled with a redirect)
- manually, by testing both unauth and auth case
- unit test
- e2e locally
> Fix loading state triggering the ErrorBoundary before its completion

- frontend/locales/en/strings.json
- frontend/src/components/help-panel/TitleDescriptionHelpPanel.tsx
- frontend/src/old-pages/Clusters/Properties.tsx
- [Consistently align to the left copy button icon](https://github.com/aws/aws-parallelcluster-ui/commit/18e81a989482f1005d2dab33cb0b9d64c00a0764)
- [Remove external icon from help panel links](https://github.com/aws/aws-parallelcluster-ui/commit/634b789b9b4deea78f0ed4f2e1d768c8696a87ee) 
- verified the affected components on my local environment
https://cloudscape.design/patterns/general/help-system/
> Consistent styling of help panel links and copy buttons

- frontend/src/__tests__/GetVersion.test.ts
- frontend/src/components/__tests__/useLoadingState.test.tsx
- frontend/src/components/useLoadingState.tsx
- frontend/src/model.tsx
- frontend/src/old-pages/Clusters/FromClusterModal/__tests__/useClustersToCopyFrom.test.tsx
- frontend/src/types/base.tsx
This PR moves the request for the PC version into the initial load happening before booting the app. This is due to the fact that the rest of the app behaves as if the version is always present, and could crash if the version is not there for some reason.
This also fixes a crash happening whenever the `get_version` call takes too much time to respond, causing the code accessing the version to crash unexpectedly. In order to reproduce, simply add a timeout in the `GetVersion` command
- refactor `GetVersion` to an async function
- remove major, minor and patch values from the store, since they are never accessed
- call `GetVersion` in `useLoadingState`
- remove `GetVersion` call from the `LoadInitialState`
- manually, by verifying the crash does not happen anymore
- unit tests
- e2e tests …
> Fetch PC version during initial load

- infrastructure/environments/demo-cfn-update-args.yaml
- infrastructure/parallelcluster-ui.yaml
This PR bumps the default PC version installed with PCUI to 3.5.1 (as per the screenshot below)
- bump default PC version in CFN template
- bump PC version deployed to our demo env
- manually, by updating the demo environment with the `./infrastructure/update-environment-infra.sh demo` script
- manually, by uploading the CFN template via the console (see screenshot)
> Bump default PCluster version to 3.5.1

- frontend/src/components/Status.tsx
- frontend/src/components/__tests__/Status.test.tsx
- frontend/src/old-pages/Clusters/__tests__/Clusters.test.tsx
- frontend/src/old-pages/Images/CustomImages/CustomImageDetails.tsx
- frontend/src/old-pages/Images/CustomImages/CustomImages.tsx
- extracted a function to apply sentence case formatting to statuses
- added `StatusIndicator` to Custom images
Verified locally status indicators under:
- cluster list and details
- stack events
- custom images list and details
> Format status indicators according to guidelines

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Components.module.css
- frontend/src/old-pages/Configure/Queues/MultiInstanceComputeResource.tsx
- frontend/src/old-pages/Configure/Queues/Queues.tsx
- frontend/src/old-pages/Configure/Queues/SingleInstanceComputeResource.tsx
- [Show the remove compute resource button also for the first item](https://github.com/aws/aws-parallelcluster-ui/commit/4ce5f15a6ef7614a54b78d3a041ac3afdcbbc227)
- [Move queues advanced options inside footer](https://github.com/aws/aws-parallelcluster-ui/commit/f312ff1277389c1341e352bcfd12f6e31821777d)
- [Move placement group checkbox near SubnetID](https://github.com/aws/aws-parallelcluster-ui/commit/09b23b7fbce085ce5fb35ae0cc5a85d8f196f8ea)
- [Use h4 header for compute resource name](https://github.com/aws/aws-parallelcluster-ui/commit/dfa62df63ee1e8627d8142d4f55c20b281bd0741)
In order to increase the likelihood of your contribution being accepted, please make sure you have read both the [Contributing Guidelines](../CONTRIBUTING.md) and the [Project …
> Queues UI fixes

- frontend/src/components/Status.tsx
- frontend/src/old-pages/Images/CustomImages/CustomImageDetails.tsx
Inspected an existing custom image and the AMI state is displayed correctly
> Add StatusIndicator to AMI state inside custom images

- frontend/src/old-pages/Clusters/Instances.tsx
Currently when clicking Start or Stop button on a cluster instance, when loading is terminated the button is still in enabled state.
The issue is rooted in the fact that `instances` is continuously fetched from the backend, its content changes, but the `selectedInstances` keeps a reference to the old/stale value.
This PR aims at solving this issue by obtaining `selectedInstances` value directly from `instances` through a filter operation.
* Verified that when clicking Stop button after the loading state the button is disabled
* Verified that when clicking Start button after the loading state the button is disabled
In order to increase the likelihood of your contribution being accepted, please make sure you have read both the [Contributing Guidelines](../CONTRIBUTING.md) and the [Project …
> Fix Start and Stop instances button still enabled after being clicked once

- frontend/src/old-pages/Configure/Storage.tsx
- frontend/src/old-pages/Configure/Storage/AddStorageForm.tsx
This PR updates the layout of the Storage section, with the goals of:
- grouping together related fields
- stacking fields vertically in a single-column layout
- make the Multiselect of the Add Storage section the same size of the other fields
- reorganize shared fields
- reorganize fields in EBS, EFS and Fsx Lustre
**Please note:** introducing a single column layout also where a smaller second column had been designed (e.g. volume size). This is due to how responsive layouts are implemented in CloudScape, which makes it very hard to create a custom grid within a ColumnLayout, which is within a Wizard component itself.
**Add storage section**
**Sample storage layout: EFS**
**Sample storage layout: FSX for Lustre**
**Sample storage layout: EBS**
**Sample storage layout: OpenZFS and ONTAP** …
> Update Storage section layout 

- frontend/locales/en/strings.json
- frontend/src/__tests__/CreateCluster.test.ts
- frontend/src/model.tsx
- frontend/src/old-pages/Configure/Create.tsx
- [Remove disable rollback when creating a cluster](https://github.com/aws/aws-parallelcluster-ui/commit/68a90238bf4809a32d4b7729a7072a521502b2c7)
- [Remove extra spacing from Create container when no errors are shown](https://github.com/aws/aws-parallelcluster-ui/commit/48e7cd58eb9d4f08e201a6d5e362eb64ad082c97)
- Dry run and create works fine locally
> Remove disable rollback when creating a cluster

- frontend/src/old-pages/Configure/Storage.tsx
> Add external icon to storage description link

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Storage.tsx
- frontend/src/old-pages/Configure/Storage/__tests__/validateEfs.test.ts
- frontend/src/old-pages/Configure/Storage/storage.validators.ts
Currently in EFS storage settings, if the provisioned throughput checkbox is selected and then deselected, the corresponding parameter `ProvisionedThroughput` is not cleared from the state, resulting in the final YAML.
This PR aims at solving the aforementioned issue, by:
* Clearing the state when the checkbox is unselected
* Set the provisioned throughput as `number` and not `string`, as specified in [ParallelCluster Docs](https://docs.aws.amazon.com/parallelcluster/latest/ug/SharedStorage-v3.html#yaml-SharedStorage-EfsSettings-ProvisionedThroughput)
* Adding a validator (and a corresponding error message) to check that the provided value is not null
* Unit tests
* Manual tests
* Verified that when checkbox is checked default value is `128`
* Verified that when checkbox is checked and …
> Clear ProvisionedThroughput in EFS storage when corresponding checkbox is unchecked

- frontend/src/components/TopBar.tsx
- frontend/src/components/__tests__/TopBar.test.tsx
This PR disabled the region selector in the TopNavigation bar, when user is in the cluster creation wizard. The region can still be changed via the dedicated region selector in the Cluster section of the wizard.
- disable region selector only in `/configure` page
- use CloudScape disabled text color 
- manually, by changing region in Clusters, Images and Users section
- manually, by checking that users cannot change regions in both create and edit cluster
- unit test
- [Design tokens](https://cloudscape.design/foundation/visual-foundation/design-tokens/)
By submitting this pull …
> Disable region selector in TopBar when in Wizard

- frontend/src/__tests__/CreateCluster.test.ts
- frontend/src/model.tsx
- frontend/src/types/base.tsx
Adds discoverability of clusters created through ParallelCluster UI.
- dry run passes with no tags specified in the YAML
- dry run passes with additional tags specified in the YAML
- the new tag is present in the cluster YAML config after it has been built and on the EC2 instances
> Apply custom product tags before a cluster is created

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Create.tsx
Make cluster creation to be consistent with Cloudscape guidelines.
* Removed spinner below YAML code editor
* Added an in-progress flashbar at the top of the page
* Manually on local environment
* Verified when dry-run is clicked loading state is shown
* Verified when create is clicked loading state is shown
Upon dry-run failure or success the flashbar is dismissed.
Upon create success the user is redirected to Clusters page.
> Add create cluster loading flashbar

- frontend/src/feature-flags/__tests__/FeatureFlagsProvider.test.ts
- frontend/src/feature-flags/featureFlagsProvider.ts
Enable flagged features by acting on `sessionStorage`. For example:
Define a new feature flag
```typescript
export type AvailableFeature = 'cost'
```
Open a browser tab with PCUI, then go to the console and type
```typescript
window.sessionStorage.setItem('additionalFeatures', '["cost"]')
```
Reload the page and the `cost` flag will be active!
Repeated the same procedure explained in the description (on Chrome)
> Enable additional features by using sessionStorage

- frontend/src/components/TopBar.tsx
Reduces the calls made when a user switches region using the top bar.
**N.B.: some calls are still duplicated (images) because they are loaded as a side effect of `/get_aws_configuration`. It will be fixed in a separate PR.**
Changed the region using the TopBar.
Before:
After:
Verified also that a cluster can be created after having switched the region.
> Remove unnecessary HTTP calls when changing region using the TopBar

- frontend/locales/en/strings.json
- frontend/src/model.tsx
- frontend/src/old-pages/Configure/Create.tsx
* Make cluster loading flashbar message to be dismissable
* Closes #179 
* Manually tested on local environment
* Dry-run both successful and unsuccessful: verified that flashbar message is dismissed
* Create successful: verified that flashbar message is not automatically dismissed and selected region is changed before redirect
* Create unsuccessful: verified that flashbar message is dismissed
> Force dismiss of cluster loading message upon cluster creation and change current region to the one of the created cluster

- infrastructure/parallelcluster-ui.yaml
This PR adds support for PC API template version 3.6.0 onwards, since three parameters (related to the previous implementation) are not needed anymore and when passed to a 3.6.0 template, they cause an error.
- added two conditions to check if PCUI is getting deployed with a PC API template supporting docker or not
- added an IF statement for the three parameters that are not needed with PC API template version 3.6.0
NB: I didn't change the existing conditions (which would have resulted in a streamlined parameter passing) to make it super clear what happens when passing those three parameters.
- manually on my account
In order to increase the likelihood of your contribution being accepted, please make sure you have read both the [Contributing Guidelines](../CONTRIBUTING.md) and the …
> Support PC API 3.6.0 cloudformation template

- frontend/src/old-pages/Configure/Cluster.tsx
- frontend/src/old-pages/Configure/HeadNode.tsx
- frontend/src/old-pages/Configure/Queues/Queues.test.tsx
- frontend/src/old-pages/Configure/Queues/Queues.tsx
- frontend/src/old-pages/Configure/Queues/queues.types.ts
Reduce cross-AZs costs by selecting the same subnet of the HeadNode for the queues.
- Kept the default subnet assigned to the Head node: the same subnet is assigned to the queue and dry run succeeds
- Changed the default subnet assigned to the Head node: the same subnet is assigned to the queue and dry run succeeds
- [] I checked that login and logout work as expected
> Set queue subnet to the same HeadNode subnet

- frontend/locales/en/strings.json
- frontend/src/feature-flags/featureFlagsProvider.ts
- frontend/src/feature-flags/types.ts
- frontend/src/old-pages/Configure/Configure.tsx
- frontend/src/old-pages/Configure/Queues/Queues.test.tsx
- frontend/src/old-pages/Configure/Queues/Queues.tsx
- frontend/src/old-pages/Configure/Queues/queues.types.ts
This PR introduce a new  `new_resources_limits` feature flag for versions >= 3.6.0. If feature flag is enabled, resources limits are set as follows:
* Max queues: 100
* Max compute resources: 40
Furthermore, a cluster can have a maximum of a total of 150 compute resources.
* Unit tests
* Manual tests on Queues page
* Verified that queues and compute resources buttons are enabled/disabled as expected
> Introduce 'new_resources_limits' feature flag for versions >= 3.6.0 and set limits accordingly

- requirements.in
- requirements.txt
Upgraded pytest to 7.2.2
- manually, launching unit tests and seeing them all green
- https://github.com/aws/aws-parallelcluster-ui/security/dependabot/8
> Upgrade pytest to 7.2.2 to remove dependency on py module affected by security issue

- frontend/locales/en/strings.json
- frontend/src/old-pages/Clusters/Actions.tsx
- frontend/src/pages/index.tsx
This PR removes the dedicated cost monitoring page. It is related to #218 , but can be safely merged in any order since the whole feature is behind an experimental flag
> Remove dedicated cost monitoring page

- .gitignore
- infrastructure/parallelcluster-ui.yaml
- scripts/build_lambda_archive.sh
This PR introduces a script to package PCUI code as a zip archive for Lambda deployment.
It also edits the main CloudFormation template `parallelcluster-ui.yaml` to allow the lambda deployment and correctly set everything up (otherwise it would have not been possible to test the changes).
This assumes that the Lambda code archive is available in the same bucket where infrastructure CloudFormation templates are available.
Right now the script outputs all the info from the various commands it executes.
The produced archive will be available at the path from the two specified mandatory parameters.
Check the `build_lambda_archive.sh` top file comments for example on its usage.
**NB**: Right now only tests files are removed from the package. In a future PR we will separate dev dependencies and …
> Added script for lambda code archive building + adapted main template for deployment

- frontend/locales/en/strings.json
- frontend/src/old-pages/Clusters/Costs/EnableCostMonitoringButton.tsx
- frontend/src/old-pages/Clusters/Costs/__tests__/useActivateCostMonitoringMutation.test.tsx
- frontend/src/old-pages/Clusters/Costs/costs.queries.tsx
This PR adds a modal to help users who need [to manually enable Cost Explorer](https://docs.aws.amazon.com/cost-management/latest/userguide/ce-enable.html).
Following PRs will:
- enable the whole cost monitoring feature with a non-experimental flag
- add e2e spec
- update `useActivateCostMonitoringMutation` to delegate handling of error and success
- when Cost Explorer needs to be manually activated, show modal
- manually, by mocking both a 400 and a 405
- manually, by mocking a 204
- unit tests
- https://docs.aws.amazon.com/cost-management/latest/userguide/ce-enable.html
By …
> Add modal to help users to manually activate Cost Explorer

- frontend/src/feature-flags/__tests__/FeatureFlagsProvider.test.ts
- frontend/src/feature-flags/featureFlagsProvider.ts
- frontend/src/old-pages/Clusters/Costs/__tests__/EnableCostMonitoringButton.test.tsx
- frontend/src/old-pages/Clusters/Costs/__tests__/useCostMonitoringStatus.test.tsx
This PR activates Cost Monitoring starting from PC 3.2.0. 
- bind the `cost_monitoring` flag to the PC version >= 3.2.0)
- verify CM activates with sessionStorage being empty
- verify CM does not activate mocking the version to 3.1.0
- unit tests
> Enable Cost Monitoring starting from PC 3.2.0

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Create.tsx
Remove the misleading success flashbar after the create cluster request is completed. It's misleading because cluster creation is an asynchronous process that can fail.
Created a cluster and no green flashbar is displayed
> Remove success loading bar after creating a cluster

- frontend/src/feature-flags/__tests__/FeatureFlagsProvider.test.ts
- frontend/src/feature-flags/featureFlagsProvider.ts
- frontend/src/old-pages/Configure/Queues/Queues.test.tsx
- frontend/src/old-pages/Configure/Queues/Queues.tsx
This PR updates the scheduling resources limits introduced with #211. It also activates the feature for PC versions greater or equal to 3.6.0
- update limits
- disallow creation of a new queue when the per-cluster total has been reached
- manually, by activating the feature and testing the limits
- manually, by disablign the feature and testing the limits
- unit tests
> Update and activate increased resource limits for PC >= 3.6.0

- frontend/src/old-pages/Configure/Configure.tsx
- frontend/src/old-pages/Configure/Create.tsx
This PR disables the action buttons in the cluster creation wizard while a dry-run/create/edit request is pending
- add/remove loading state when performing a dry-run, a creation and an update
- bind both the wizard and the dryrun button to such loading state
- manually, by testing dry-run, create and edit
> Add loading state to wizard action buttons

- frontend/src/old-pages/Configure/Components.tsx
- frontend/src/old-pages/Layout.tsx
- frontend/src/old-pages/Logs/index.tsx
Fixes #181.
Override breadcrumb navigation using `react-router-dom` instead of a page reload (took inspiration from the sidebar).
- Clicked on many breadcrumb items: no page reload and the region is preserved
- Started a cluster creation and clicked on a breadcrumb: the user is redirected to cluster and form data is resetted
> Don't reload the page when clicking on a breadcrumb

- frontend/src/old-pages/Clusters/Costs/CostData.tsx
This PR updates the link pointing to Cost Explorer, so that it opens up with the following pre-filled filters:
- granularity: monthly
- time range: last 12 months
- cluster-name: selected cluster
- no groupby
- manually, by clicking the link and verifying the chart is the last 12 months, for the selected cluster
> Update link pointing to Cost Explorer with pre-filled filters

- frontend/src/old-pages/Configure/Create.tsx
This PR fixes an issue preventing the cluster details to be loaded right after the cluster creation.
Fixes #230 
- remove forced cluster selection before redirecting to the cluster details
- manually, by creating a cluster and checking the cluster details get loaded correctly
> Fix cluster details not being loading after creation

- infrastructure/parallelcluster-ui.yaml
This PR addresses the deployment issue related to a Cost Explorer policy being deployed in GovCloud region.
The fix is not deploy that specific part of the CostMonitoringAndPricingPolicy.
NB: the name of the policy has been left unchanged since changing it right now doesn't provide much value.
This PR doesn't solve any issues since the fix needs to be addressed at code level also.
- manually in my personal account
> Fix deployment for GovCloud region us-gov-west-1

- infrastructure/environments/demo-cfn-update-args.yaml
- infrastructure/parallelcluster-ui.yaml
This PR bumps the default PC version installed with PCUI to 3.6.0 (as per the screenshot below)
- bump default PC version in CFN template
- bump PC version deployed to our demo env
- manually, by updating the demo environment with the `./infrastructure/update-environment-infra.sh` demo script
- manually, by uploading the CFN template via the console (see screenshot)
> Bump default PCluster version to 3.6.0

- frontend/src/feature-flags/__tests__/FeatureFlagsProvider.test.ts
- frontend/src/feature-flags/featureFlagsProvider.ts
- frontend/src/feature-flags/useFeatureFlag.ts
- frontend/src/old-pages/Clusters/Costs/__tests__/EnableCostMonitoringButton.test.tsx
- frontend/src/old-pages/Clusters/Costs/__tests__/useCostMonitoringStatus.test.tsx
- frontend/src/old-pages/Configure/Queues/Queues.tsx
- frontend/src/old-pages/Configure/Queues/__tests__/mapComputeResources.test.ts
- frontend/src/old-pages/Configure/Queues/queues.mapper.ts
- frontend/src/old-pages/Configure/util.tsx
Closes https://github.com/aws/aws-parallelcluster-ui/issues/236.
* Unit tests
* Manual tests targeting demo environment with local changes (could not directly test deployment in `us-gov-west-1`)
* If `eu-west-1` is marked as not supported for `cost_monitoring` feature, no API calls is made to `/cost-monitoring` endpoint neither the tab is shown in cluster details page. 
* Viceversa, if `eu-west-1` is supported for `cost_monitoring` feature API calls are executed successfully and the 'Cost monitoring' tab is shown as expected
* https://github.com/aws/aws-parallelcluster-ui/issues/236
* https://github.com/aws/aws-parallelcluster-ui/issues/213
In order to increase the likelihood of your contribution being accepted, please make sure you have read both the [Contributing …
> Disable Cost Monitoring in unsupported regions

- infrastructure/parallelcluster-ui-cognito.yaml
- infrastructure/parallelcluster-ui.yaml
Add PermissionBoundary for every IAM role and prefix for every IAM role and policy.
> [PCUI]Add PermissionBoundary for every IAM role and prefix for every IAM role and policy.

- .gitignore
- DEVELOPMENT.md
1. Add development instructions to `DEVELOPMENT.md`.
2. Add to gitignore: idea folder and personal env files.
No test needed.
> [Doc] Add development instructions to DEVELOPMENT.md + folders to gitignore

- DEVELOPMENT.md
- api/PclusterApiHandler.py
- frontend/locales/en/strings.json
- frontend/src/__tests__/storageCreationValidation.test.tsx
- frontend/src/feature-flags/__tests__/FeatureFlagsProvider.test.ts
- frontend/src/feature-flags/featureFlagsProvider.ts
- frontend/src/feature-flags/types.ts
- frontend/src/model.tsx
- frontend/src/old-pages/Configure/Storage.tsx
- frontend/src/old-pages/Configure/Storage.types.ts
- frontend/src/old-pages/Configure/Storage/storage.mapper.ts
- infrastructure/environments/demo-cfn-update-args.yaml
- infrastructure/parallelcluster-ui.yaml
Add support for ParallelCluster 3.7.0
1. pcluster version bumped to 3.7.0 in CloudFormation template and demo env.
2. 3.7.0 features added to feature flags provider + new unit tests covering it.
3. Add Amazon File Cache as a supported shared storage within the Wizard (both frontend and backend changes). This change was considered out of scope at first, but discovered that it was actually easier to introduce it than modifying the inner logic to silently avoid it. Moreover we are providing feature parity for File Cache that is certainly valuable for our users.
4. Documentation: added to DEVELOPMENT.md some valuable information about development process learned during this iteration.
1. With this change we are not achieving the full feature parity with ParallelCluster 3.7.0. In fact we are …
> Add support for ParallelCluster 3.7.0

- frontend/src/feature-flags/__tests__/FeatureFlagsProvider.test.ts
- frontend/src/feature-flags/featureFlagsProvider.ts
- frontend/src/feature-flags/types.ts
- frontend/src/old-pages/Configure/Queues/SlurmMemorySettings.tsx
- frontend/src/old-pages/Configure/Queues/__tests__/hasMultipleInstanceTypes.test.tsx
Add support for Memory Based Scheduling with Multiple Instance Types in ParallelCluster 3.7.0+.
**Known Limitations**
The wizard does not remove the schedulable memory property in the resulting cluster config when mem based scheduling is enabled and then disabled. This is not a blocking bug because the resulting cluster config is valid, but simply an unexpected behaviour that we may decide to address in another iteration.
1. Unit tests
2. Manual verification with Pcluster 3.7.0: mem based scheduling can be toggled and preserved with input cluster config when using multiple instance types in 3.7.0. Verified with dryrun creation.
3. Manual verification with Pcluster 3.6.0: feature flagging is working as expected prohibiting the use of mem based scheduling with multiple instance types. …
> [Frontend] Add support for Memory Based Scheduling with Multiple Instance Types in ParallelCluster 3.7.0+.

- frontend/src/__tests__/GetCostMonitoringStatus.test.ts
- frontend/src/model.tsx
Avoid surfacing errors in the UI that are caused by failures in interacting with Cost Explorer, regardless the failure root cause.
1. Replaced the error notification at the UI level with a console log
2. Added unit tests to cover the scenario
1. Unit tests
2. Manual test verifying that errors are not displayed in the UI when access to Cost Explorer is forbidden by a permissions boundary
3. Manual test verifying that the cost monitoring feature behaves as expected in the UI when the permission boundary is removed and the access to Cost Explorer has recovered.
> [Frontend] Avoid surfacing errors in the UI that are caused by failures in interacting with Cost Explorer, regardless the failure root cause.

- infrastructure/environments/demo-variables.sh
- infrastructure/update-environment-infra.sh
Add possibility to specify the infrastructure bucket name directly, rather than referencing the CloudFormation stack that deploys it.
Used to update personal environment, where the infra bucket stack does not exists, but only the bucket.
> [Ops] Add possibility to specify the infrastructure bucket name

- frontend/src/util.ts
Add default cluster user for Ubuntu22.
Without this change, the default cluster user for Ubuntu22 falls back to 'ec2-user' making part of the UI to fail (Job Status panel).
Verified that with the proposed fix, the job status panle does not return any error and the subvmitted request to the backend has the expected cluster user.
> Add default cluster user for Ubuntu22.

- frontend/src/__tests__/util.test.tsx
Unit tests to cover the retrieval of default cluster user.
Unit tests
> [Test] Add unit tests to cover the retrieval of default user by OS.

- scripts/build_and_release_image.sh
Build and Release Image: use ecr-public command when targeting ECR public endpoint and standard ecr otherwise.
With this change we can reuse the same script used to deploy PCUI official image to deploy a test image in our personal account.
1. Used to deploy PCUI image in personal account
2. Verified that the variable ECR_COMMAND is populated as expected when targeting public ECR.
> [Ops] Build and Release Image: use ecr-public command when targeting ECR public endpoint and standard ecr otherwise.

- infrastructure/parallelcluster-ui.yaml
Add fsx:DescribeFileCaches to ParallelClusterUIUserRole so that the wizard is able to list existing File Caches.
Verified in personal environment that adding such policy allows the wizard to list existing File Caches.
> [Infrastructure] Add fsx:DescribeFileCaches to ParallelClusterUIUserRole

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Storage.tsx
Fix label/placeholder used by the Wizard for existing EBS volumes.
Before this change the wizard showed the placeholder "i.e., fsx-1234 or efs-1234" as hint for existing EBS volumes, whereas it should rather be "i.e., vol-1234".
1. Tested in personal environment that the wizard shows the expected label and placeholder
2. Verified with git-grep that there is no occurrence of the local string `wizard.storage.Ebs.existing`., which has been removed in this change.
> [Frontend] Fix label/placeholder used by the Wizard for existing EBS volumes

- infrastructure/parallelcluster-ui.yaml
Reduce ID and Access Token validity from 10 to 5 minutes.
This is a best practice to improve the security posture of the product as it reduces the operability time of a potential malicious token.
[ONGOING] Deployed in test environment and verified that a user session works as expected for more than 5 minutes.
> [Infrastructure] Reduce ID and Access Token validity from 10 to 5 minutes.

- frontend/package-lock.json
Cherry picked from https://github.com/aws/aws-parallelcluster-ui/pull/278
Bumps [@babel/traverse](https://github.com/babel/babel/tree/HEAD/packages/babel-traverse) from 7.18.6 to 7.23.2.
- [Release notes](https://github.com/babel/babel/releases)
- [Changelog](https://github.com/babel/babel/blob/main/CHANGELOG.md)
- [Commits](https://github.com/babel/babel/commits/v7.23.2/packages/babel-traverse)
1. Local frontend build
1. Deployed PCUI in personal account and verified normal behaviour: cluster creation and navigation through pages.
> [Security] Fix CVE: Bump @babel/traverse from 7.18.6 to 7.23.2 in /frontend

- DEVELOPMENT.md
- infrastructure/environments/demo-cfn-update-args.yaml
- infrastructure/parallelcluster-ui.yaml
Bump default ParallelCluster version to 3.8.0b1, covering both production code and operational scripts.
**Notes**
The goal of this change is not to provide feature parity with ParallelCluster 3.8.0b1.
1. Deployed PCUI with pcluster 3.8.0b1
2. Created and deleted a cluster using a configuration file that triggers all the features introduced in 3.8.0b1: custom munge key, custom slurm db name, alarms, dra for fsx lustre.
> [Dependencies] Bump default ParallelCluster version to 3.8.0b1.

- infrastructure/parallelcluster-ui-cognito.yaml
- infrastructure/parallelcluster-ui.yaml
1. Add support for permissions boundary: now the user can optionally specify the IAM policies to be used as permissions boundaries for the PCUI infrastructure and the PCAPI infrastructure, separately.
2. Add support for IAM roles and policies prefix: now the user can optionally specify a prefix to be added to every IAM role and policy name created as part of both PCUI and PCAPI infrastructure.
**Note about Customer Experience**
When a permissions boundary is specified for the PCAPI infrastructure, such boundary is also set as condition for _iam:CreateRole/PutRolePolicy/DeleteRolePolicy/AttachRolePolicyDetachRolePolicy_ (this behaviour is part of the product since Jan 2023 see [commit](https://github.com/aws/aws-parallelcluster/pull/4840)).  This implies that when such boundary is …
> [Infrastructure] Add support for permissions boundary and IAM prefixes

- scripts/README.md
- scripts/common.sh
- scripts/deploy.sh
- scripts/setup-env.sh
1. Add script 'deploy.sh' to deploy (created or update) the local PCUI to a personal environment.
2. Add script 'setup-env.sh' to create the configuration files to deploy PCUI to personal environments
3. Documented how to use the above scripts.
Command to create files for the personal environment (this must be done just the first time):
```
bash scripts/setup-env.sh giacomo-env
```
Command to deploy (create or update) PCUI into the environment:
```
bash scripts/deploy.sh giacomo-env
```
Example of execution:
```
(pcluster-ui) ➜  aws-parallelcluster-ui git:(wip/mgiacomo/2023120/fix-urlib-cve) ✗ bash scripts/deploy.sh mgiacomo                            
[INFO] Selected environment: mgiacomo
[INFO] Retrieving infrastructure bucket
[INFO] Using infrastructure bucket …
```
> [Tools] Add scripts to facilitate 1-click deployment of PCUI in personal environment

- infrastructure/parallelcluster-ui.yaml
Bump ParallelCluster UI version to 2023.12.0.
> [Versioning] Bump ParallelCluster UI version to 2023.12.0.

- DEVELOPMENT.md
- infrastructure/environments/demo-cfn-update-args.yaml
- infrastructure/parallelcluster-ui.yaml
Bump Pcluster version to 3.8.0.
1. Deployed in personal account
2. Navigated pages
3. Verified that the wizard does not introduce any block to the submission of a cluster configuration for 3.8.0.
> [Dependencies] Bump Pcluster version to 3.8.0.

- requirements.in
- requirements.txt
1. Upgrade Werkzeug to version 2.3.8.
These upgrades solve the following PRs:
1.. https://github.com/aws/aws-parallelcluster-ui/pull/290
And the following CVEs:
1.. https://github.com/aws/aws-parallelcluster-ui/security/dependabot/26
1. PCUI deployed
2. Navigated main pages
3. Tested cluster creation
> [Dependencies] Upgrade Werkzeug

- infrastructure/parallelcluster-ui.yaml
Add EC2 permissions required by PCUI private deployment only when private deployment is enabled.
In particular, the following permissions are required by the PCUI Lambda execution role when private deployment is enabled:
1. ec2:CreateNetworkInterface
1. ec2:DeleteNetworkInterface
1. ec2:AttachNetworkInterface
1. ec2:DescribeNetworkInterfaces
1. ec2:DescribeInstances
1. Deployed in personal environment with private deployment *disabled*: deployment succeeded, extra permissions not deployed, cluster creation succeeded.
2. Deployed in personal environment with private deployment *enable*: deployment succeeded, extra permissions are deployed, cluster creation succeeded. 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
> [Infrastructure] Add EC2 permissions required by PCUI private deployment only when private deployment is enabled.

- infrastructure/environments/demo-cfn-update-args.yaml
- infrastructure/parallelcluster-ui.yaml
1. Renamed APIG and Lambda resources to unblock stack updates to 2023.12.0. The renaming is necessary because as part of PCUI private deployment we are changing the resource.toy e without changing the resource name, which is not supported by CloudFormation updates.
It is also necessary for the Lambda Function, even if we are not changing the resource typ,e because, experimentally, wer observed that changing the vpc configuration is not supported by CloudFormation updates leading the resource to a failed updated (error: Lambda function did not stabilize) 
In particular we renamed the following resources impacted by the new feature "Private PCUI deployment":
1. ParallelClusterUIFunction
2. ApiGateway
3. ApiGatewayStage
2. Added missing stack parameters to demo env.
1. Updated demo env from …
> [Infrastructure] Rename APIG and Lambda resources to unblock stack updates to 2023.12.0 and added missing params to demo env

- infrastructure/parallelcluster-ui.yaml
Specify required ParallelCluster version for stack parameters: 
1. PermissionsBoundaryPolicy
2. PermissionsBoundaryPolicyPCAPI
3. IAMRoleAndPolicyPrefix.
> [Infrastructure] Specify required ParallelCluster version for stack parameters

- infrastructure/parallelcluster-ui.yaml
1. Specify PermissionsBoundaryPolicy and IAMRoleAndPolicyPrefix in PCAPI only if not empty. In this way the PCUI 2023.12.0 deployment can succeed even with PC >= 3.8.0.
2. Fix the parameter used in PCAPI: PermissionsBoundaryPolicyPCAPI rather than PermissionsBoundaryPolicy. This was a bug we did not notice before becausde during manual tests we have always used the same permissions boundary both for PCUI and PCAPI.
1. Deployed PCUI with PC 3.5.0
2. 1. Deployed PCUI with PC 3.8.0b1
> [Infrastructure] Specify PermissionsBoundaryPolicy and IAMRoleAndPolicyPrefix in PCAPI only if not empty.

- infrastructure/parallelcluster-ui.yaml
Upgrade Lambda runtime from Python3.7 to Python3.9
Lambda Python 3.7 runtime was deprecated earlier today https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
> Upgrade python version to 3.9

- app.py
- requirements.in
- requirements.txt
* Updated to [flask v2.3.3](https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-3-3) because it requires jinja2>3.1.2, which will close [CVE-2024-22195](https://github.com/aws/aws-parallelcluster-ui/security/dependabot/28)
* Had to update `app.py` because `JSONEncoder` became deprecated as part of flaskv2.3.0, so used `DefaultJSONProvider`: https://github.com/pallets/flask/pull/4692
Deployed stack on personal acc, and created a cluster
> [Dependencies] Bump flask version for jinja2

- requirements.in
- requirements.txt
* Use `python-jose[cryptography]` instead of just `python-jose` to use the cryptography backend instead of `ecdsa` backend
* Doing this because of this CVE for edcsa that they don't intend to fix: https://github.com/aws/aws-parallelcluster-ui/security/dependabot/29
* ecdsa will still be installed, but will be unused, since cryptography will be used instead: https://pypi.org/project/python-jose/
Ran pytest, deployed, created/deleted cluster
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> [Dependencies] Add cryptography backend for python-jose

- infrastructure/environments/demo-cfn-create-args.yaml
- Bumps pcluster version in cfn create args, missed to bump the pcluster version here from this PR https://github.com/aws/aws-parallelcluster-ui/pull/316
> [Dependencies] Bump pcluster version to 3.9.0 in cfn create args

- frontend/src/__tests__/ListClusters.test.ts
- frontend/src/model.tsx
* Paginate list clusters since it's possible that some of the clusters don't show up since previously did not paginate
* Added unit tests for testing listing clusters
* We want to use a URL instead of a body in the GET request because: https://stackoverflow.com/questions/978061/http-get-with-request-body
Deployed in personal account, created and deleted clusters
Wrote and ran unit tests
> Paginate list clusters

- DEVELOPMENT.md
- frontend/resources/attributions/npm-python-attributions.txt
Merge AFTER https://github.com/aws/aws-parallelcluster-ui/pull/311, since this adds licenses from dependencies introduced there
* Update the readme to specify changes to attribution doc
* Update attribution doc with versions being used, add licenses for new/missing dependencies
> [Docs] Update attribution doc + improve readme with editing attribution doc

- frontend/src/__tests__/util.test.tsx
- frontend/src/feature-flags/__tests__/FeatureFlagsProvider.test.ts
- frontend/src/feature-flags/featureFlagsProvider.ts
- frontend/src/feature-flags/types.ts
- frontend/src/old-pages/Configure/Cluster/OsFormField.tsx
- frontend/src/util.ts
- Added ubuntu2204 to the UI (the feature flag was already there)
- Aded Rhel9 to the UI and as a feature flag
- Added function to check for deprecation and added ubuntu 1804 as deprecated with 3.7
Deployed in personal account and created clusters with ubuntu2204 and rhe9
- Addresses this issue: https://github.com/aws/aws-parallelcluster-ui/issues/318
> Add support for Ubuntu2204 and Rhel9 in PCUI, deprecate Ubuntu1804

- frontend/src/__tests__/ListClusters.test.ts
- frontend/src/model.tsx
- Found that when paginating the nextToken has special characters that aren't getting sent properly (found there was a problem when I had ~10 clusters spun up from testing)
- The token needs to be encoded properly so I added `encodeURIComponent`
- [Axios has a special parameter `params`](https://github.com/axios/axios?tab=readme-ov-file#request-config) that can handle the special characters
- Having ~10 clusters up, without this change PCUI breaks. Before adding paginating, it only shows a couple clusters. With this fix, we can see all the clusters without any breaks
- Checked in the logs that PCUI is sending the correct API calls, they send the api calls with the proper nextToken and receive a successful response with the paginated clusters
- Unit tests pass
In order to increase the …
> [Bug] Fix get call with special characters in nextToken in listclusters

- frontend/src/components/Status.tsx
Convert status to string in formatStatus before calling replaceAll to prevent errors in JobStatus panel blocking the whole interface.
Verified that with this change, the JobStatus panel is rendered and does not block the interface with the error message.
> [Bugfix] Convert status to string in formatStatus before calling replaceAll to prevent errors in JobStatus panel blocking the whole interface.

- scripts/build_and_update_lambda.sh
- scripts/deploy.sh
Fix and improve tools used to deploy PCUI for local testing. In particular:
1. Fixed the script used to update the lambda function with local code. It was broken because it was looking for the lambda function using a wrong name.
2. Made deploy.sh able to update the lambda, so that the developer can now deploy local code with a single script. 
3. Added a success log line at the end of the above script to let the user kwno it succeeded.
1. Used both scripts to deploy PCUI for local testing.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
> [Tools] Fix and improve tools used to deploy PCUI for local testing

- api/PclusterApiHandler.py
- frontend/src/model.tsx
- frontend/src/old-pages/Clusters/Accounting.tsx
Fix issues that were breaking the rendering of accounting info
In particular:
1. fix the retrieval of compute nodes instance type to determine price estimate;
2. fix the generation of job properties rendered in the job accounting modal.
Also minor improvements to log lines related to accounting.
Manually deployed and verified that the modal showed the accounting info per job is displayed.
> [Accounting] Fix issues that were breaking the rendering of accounting info

- frontend/src/feature-flags/__tests__/FeatureFlagsProvider.test.ts
- frontend/src/feature-flags/featureFlagsProvider.ts
- frontend/src/feature-flags/useFeatureFlag.ts
Fix a bug in feature flagging that was disabling of all PC 3.2.0+ features on PC 3.10.0+.
In particular, we needed to fix the logic that compares semantic versions.
Before this change 3.10.0 and 3.10.1 were considered lower than 3.2.0 and greater than 3.1.0, so every feature between 3.2.0 and 3.9.0 was disabled.
With this fix, feature flags are correct.
Example: the feature flexible instance type was disablòed for 3.10.0 because of the bug.
With the fix it is now enabled (see screenshot)
*Note*
There is a package dedicated to semver comparison ([semver](https://www.npmjs.com/package/semver)), but it's not worth it to add an extra dependency for such an easy logic.
1. Unit tests (full suite + one new test covering the buggy case)
2. Deployed in personal account and verified that feature …
> [Feature Flag] Fix a bug in versions comparison that was disabling all PC 3.2.0+ features on PC 3.10.0+.

- api/PclusterApiHandler.py
- requirements.in
- requirements.txt
1. Upgrade cryptography from 42.0.2 to 42.0.4 to address vulnerability https://github.com/aws/aws-parallelcluster-ui/security/dependabot/30
2. Specify JWT algorithms to decode tokens to address vulnerability https://github.com/aws/aws-parallelcluster-ui/security/dependabot/33. We specify the accepted algorithms to be [RS256] as suggested by Amazon Cognito.
1. Deployed in personal environment
2. Verified that login/logout works
3. Verified that PCUI is able to list clusters in a region
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
> [Security] Address vulnerabilities: upgrade cryptography from 42.0.2 to 42.0.4 and specify JWT algorithms to decode.

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Components.tsx
- frontend/src/old-pages/Configure/Queues/MultiInstanceComputeResource.tsx
- frontend/src/old-pages/Configure/Queues/Queues.tsx
- frontend/src/old-pages/Configure/Queues/SlurmMemorySettings.tsx
- frontend/src/old-pages/Configure/Queues/queues.mapper.ts
- frontend/src/old-pages/Configure/Queues/queues.types.ts
feat: Support ODCR(On-Demand Capacity Reservations) and CB(Capacity Blocks) for PCUI
- Added `CapacityReservationTarget` select component at the compute resource level, allowing users to choose between `CapacityReservationId`, `CapacityReservationResourceGroupArn`, or none.
- Implemented dynamic placeholders to guide users on the required inputs for `CapacityReservationId` and `CapacityReservationResourceGroupArn`.
- Introduced `CAPACITY_BLOCK` as a new purchase type option in the UI.
- Automatically hide the Allocation Strategy selection when `CAPACITY_BLOCK` is selected, following the expected behavior in ParallelCluster.
- Implemented logic to automatically hide the instance type selection and exclude the `Instances` section in the YAML when `CapacityReservationId` is selected.
- Made …
> [PCUI] Support On-Demand Capacity Reservations and Capacity Blocks for PCUI

- api/PclusterApiHandler.py
Some AWS Regions have G6 and M7 instances deployed. This change adds support for those.
Add G6 and M7 instances to drop down menu.
My colleagues have been using the m7i instance type for their head nodes for a few months without any issues. 
https://aws.amazon.com/ec2/instance-types/g6/
https://aws.amazon.com/ec2/instance-types/m7a/
https://aws.amazon.com/ec2/instance-types/m7i/
> Add support for g6 and m7 family instances.

- infrastructure/environments/demo-cfn-create-args.yaml
- infrastructure/environments/demo-cfn-update-args.yaml
- infrastructure/parallelcluster-ui-cognito.yaml
- infrastructure/parallelcluster-ui.yaml
Improve user experience to configure custom domain
In particular, we added the following new optional parameters to the PCUI stack:
1. `CustomDomain`
2. `CustomDomainCertificateArn`
3. `CognitoCustomDomain`
4. `CognitoCustomDomainCertificateArn`
and the following new outputs when a custom domain is set:
1. `CustomDomainEndpoint`
2. `CognitoCustomDomainEndpoint`
Tested that the following deployments succeed:
1. Cognito Stack with default domain
2. Cognito Stack with custom domain
3. PCUI stack with default domain using an existing Cognito stack with default domain
4. PCUI stack with default domain using an existing Cognito stack with custom domain
5. PCUI stack with custom domain using an existing Cognito stack with default domain
6. PCUI stack with custom domain using an existing Cognito …
> [Custom Domain] Improve user experience to configure custom domain

- frontend/src/feature-flags/__tests__/FeatureFlagsProvider.test.ts
- infrastructure/environments/demo-cfn-create-args.yaml
- infrastructure/environments/demo-cfn-update-args.yaml
- infrastructure/parallelcluster-ui.yaml
- scripts/README.md
1. Bump PCUI version to 2024.10.0
2. PC version to 3.11.0
3. Removed misleading version number from README instructions
PCUI deployed in personal account and able to create a cluster using PC 3.11.0.
> Bump PCUI to 2024.10.0 and PC version to 3.11.0

- frontend/package-lock.json
- frontend/package.json
- requirements.in
- requirements.txt
1. Upgrade Flask-CORS to version 4.0.2 to address vulnerability: https://github.com/aws/aws-parallelcluster-ui/security/dependabot/50
1. Upgrade lint-staged to version 15.2.5 to address vulnerability: https://github.com/aws/aws-parallelcluster-ui/security/dependabot/44
1. Flask-CORS upgrade tested by deploying PCUI on personal env and verified basic funcitonalities (navigation through pages, cluster creation and description)
2. lint-sdtage upgrade tested by running `npm run lint`
> [Dependencies] Upgrade Flask-CORS and lint-stage to address CVEs

- frontend/src/old-pages/Configure/Queues/MultiInstanceComputeResource.tsx
- Ensure CapacityReservationTarget fields (CapacityReservationId and CapacityReservationResourceGroupArn) are retained when creating a new cluster from an existing one.
- Fix issue where CapacityReservationTarget values were cleared upon navigating back and forth in the wizard.
- Manually test works as expected
> [Bug Fix] Retain ODCR settings when copying clusters and navigating steps

- api/PclusterApiHandler.py
Add support for instance family p5.
This change is required because in PC 3.10.0 we introduced the support for p5 and with PC 3.11.0 we introduced the support for p5e.
Deployed in personal account and verified that p5 instance types are shown in the dropdown both for head node and compute nodes.
> [Instance Type] Add support for instance family p5.

- frontend/src/feature-flags/__tests__/FeatureFlagsProvider.test.ts
- infrastructure/environments/demo-cfn-create-args.yaml
- infrastructure/environments/demo-cfn-update-args.yaml
- infrastructure/parallelcluster-ui.yaml
**DO NOT MERGE UNTIL PC 3.11.1 IS OUT**
Bump ParallelCluster version to 3.11.1.
From PCUI perspective, there is no change between 3.11.0 and 3.11.1 and we already extensively tested the support for 3.11.0.
> [Dependencies] Bump ParallelCluster version to 3.11.1.

- infrastructure/parallelcluster-ui.yaml
Explicitly set the policy for ECR private repo so prevent policy removal on stack update impacting Lambda function.
The minimum set of permissions required by Lambda to fetch the code from the repository is: 
* `ecr:BatchGetImage`
* `ecr:GetDownloadUrlForLayer`
However, Lambda sets the policy with the below extra permissions when the policy is not set m(current behavhoir on stack create):
* `ecr:DeleteRepositoryPolicy`
* `ecr:GetRepositoryPolicy `
* `ecr:SetRepositoryPolicy `
So we decided to go with the permissions currently set by Lambda to prevent impacts.
We will restrict the permissions once Lambda will confirm that they are enough.
Deployed in personal account and verified that:
1. ECR repo policy is retained across stack updates
2. Lambda is fully functional before and after stack …
> [BugFix] Explicitly set the policy for ECR private repo so prevent policy removal on stack update impacting Lambda function

- infrastructure/parallelcluster-ui.yaml
- This PR removes the extra ECR policy actions `ecr:DeleteRepositoryPolicy`, `ecr:GetRepositoryPolicy`, and `ecr:SetRepositoryPolicy` from our CloudFormation template. 
- As confirmed by the Lambda team, Lambda only needs `ecr:BatchGetImage` and `ecr:GetDownloadUrlForLayer` to pull images from ECR. The additional three permissions are used only when Lambda has to manage a repository policy that doesn’t already exist. 
- By explicitly defining the minimal set of permissions in our template, we prevent CloudFormation from overwriting or deleting them during future updates.
- Deployed to a personal AWS account with only BatchGetImage and GetDownloadUrlForLayer.
- Verified that Lambda can still successfully fetch images from ECR.
- Repeated stack updates (e.g., adding tags) to confirm the …
> [develop] Restrict extra permissions for ECR private repo as Lambda team has confirmed they are unnecessary

- requirements.in
- requirements.txt
Upgrade dependencies to address vulnerabilities. In particular:
* requests to 2.32.0 (from 2.31.0) to address https://nvd.nist.gov/vuln/detail/cve-2024-35195
* urllib3 to 1.26.19 (from 1.26.18) to address https://nvd.nist.gov/vuln/detail/cve-2024-37891
* cryptography to 43.0.1 (from 42.0.4) to address https://cwe.mitre.org/data/definitions/1395.html
* certifi to 2024.7.4 (from 2023.7.22) to address https://nvd.nist.gov/vuln/detail/cve-2024-39689
* jinja2 to 3.1.5 (from 3.1.3) to address https://nvd.nist.gov/vuln/detail/CVE-2024-56201 and https://nvd.nist.gov/vuln/detail/CVE-2024-56326
PCUI deployed from scratch on personal account. 
Used the deployment to login/logout create/update/delete cluster
In order to increase the likelihood of your contribution being accepted, please make sure you …
> [Dependencies] Upgrade dependencies to address vulnerabilities.

- scripts/tail-logs.sh
Add script to tail logs of a PCUI deployment by referencing the environment name.
This script helps saving some time while doing PCUI testing.
It';s enough to run `bash scripts/tail-logs.sh [ENV_NAME]`
to tail the logs for the deployed environment, without the need to navigate to the CFN and CW Console.
Used the script to tail the logs during a real investigation.
> [Ops] Add script to tail logs of a PCUI deployment by referencing the environment name.

- scripts/build_and_release_image.sh
- scripts/build_and_update_lambda.sh
Fix scripts used to deploy and update PCUI by adding provenance flag to docker build commands.
Such flag is required to make the deployment succeed with the newer version of docker CLI on M1/M2/M3 laptops.
The option is used to relax some checks in the manifest.
This change is safe as it is impacting only the way we deploy PCUI for local testing purposes.
See https://www.reddit.com/r/aws/comments/1hf3rrq/struggling_to_deploy_docker_image_to_aws_lambda/
Before this change the deployment script was failing both on creating and updating the PCUI deployment due to a manifest error. With this option they both succeed.
> [Ops] Fix scripts used to deploy and update PCUI by adding provenance flag to docker build commands.

- awslambda/serverless_wsgi.py
Upgrade `serverless_wsgi.py ` to version 3.0.5 https://github.com/logandk/serverless-wsgi/releases/tag/3.0.5
We were using a very old version back to 2016. It was not causing any issue, but it was a blocker for the upgrade of Werkzeug to version 3+, which requires `serverless_wsgi.py ` v3.0.3+
PCUI successfully deployed and working as expected.
> [WSGI] Upgrade serverless_wsgi.py to version 3.0.5

- requirements.in
- requirements.txt
Upgrade Werkzeug to version 3.0.6 (from 2.3.8).
Deployed PCUI and verified it works by navigating pages and creating a cluster.
> [Dependencies] Upgrade Werkzeug to version 3.0.6 (from 2.3.8).

- frontend/package-lock.json
- frontend/package.json
Upgrade Axios to version 1.7.8 (from 1.6.7) to address vuln https://github.com/aws/aws-parallelcluster-ui/security/dependabot/45
Deployed PCUI, navigated pages and submitted cluster creation through wizard.
> [Dependencies] Upgrade Axios to version 1.7.8 (from 1.6.7).

- frontend/package-lock.json
- requirements.txt
Bump idna from 3.4 to 3.7
Upgrade nanoid to 3.3.8.
`npm install and npm audit`
Deployed the changes and created a very basic cluster
> [Dependency] Upgrade Idna and nanoid

- requirements.in
- requirements.txt
Upgrade python-jose to 3.4.0 to address Vulnerabilities https://github.com/aws/aws-parallelcluster-ui/security/dependabot/64
*  python-jose 3.4.0 depends on pyasn1<0.5.0 and >=0.4.1
`bash scripts/deploy.sh my-env` and created a basic 3.11.1 cluster
> [Dependency] Upgrade python-jose to 3.4.0.

- infrastructure/parallelcluster-ui.yaml
[BREAKING CHANGE] Remove default value for PC version. Now the user must specify the PC version to use.
From developer perspective, this means that we do not need to do a new release of PCUI only to bumo the default PC version.
We already tested that the current release candidate is compatible with PC 3.12.0 (latest release) and 3.13.0 (next release candidate)
> [BREAKING CHANGE] Remove default value for PC version. Now the user must specify the PC version to use.

- frontend/src/feature-flags/__tests__/FeatureFlagsProvider.test.ts
- infrastructure/environments/demo-cfn-create-args.yaml
- infrastructure/environments/demo-cfn-update-args.yaml
Bump PC version to 3.12.0 in demo env and unit test
We validated that PCUI is compatible w/ PC 3.12.0.
> [Test] Bump PC version to 3.12.0 in demo env and unit test

- infrastructure/parallelcluster-ui.yaml
Fix PCUI private deployment by making the PCUI template use and return the correct URLs
1. Deployed using the private deployment infrastructure created with 1-cl;ick template in https://github.com/aws/aws-parallelcluster-ui/pull/400.
2. Verified that the correct VPCE URL is returned as output
3. Verified that Cognito now redirects to the correct PCUI URL
4. Verified that. PCUI is accessible only from the DCV instance deployed in the same VPC, having perms to access the VPCE
5. Navigated PCUI pages checking that no errors are logged interacting with the PCAPI.
Also validated with a standard PCUI deployment to verify no regressions have been introduced.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> [Infrastructure] Fix PCUI private deployment by making the PCUI template use and return the correct URLs

- .github/workflows/demo_deploy.yml
- .github/workflows/production_release.yml
- .github/workflows/pull_request.yml
Run GitHub workflows using latest Ubuntu vrsion rather than Ubuntu 20.04 as 20.04 has been deprecated in workflows. 
See https://github.com/actions/runner-images/issues/11101
PR checks in this Pr runs.
> [Workflows] Run GitHub workflows using latest Ubuntu version rather than Ubuntu 20.04

- infrastructure/parallelcluster-ui.yaml
Group storage policies and SSM policies to reduce the number of policies attached to the PCUI lambda role.
This change is required to leave space for future policies since the maximum number of attachable policies is 10.
Deployed and checked that PCUI has all the required storage and SSM permissions.
> [Policies] Group storage policies and SSM policies to reduce the number of policies attached to the PCUI lambda role

- api/PclusterApiHandler.py
- api/tests/test_utils.py
- api/utils.py
- infrastructure/parallelcluster-ui.yaml
Fix the retrieval of job info by making the SSM command to store the outputs on CloudWatch logs to prevent truncation.
This change fixes https://github.com/aws/aws-parallelcluster-ui/issues/376
Verified that PCUI is now able to show information when 200+ jobs are submitted.
In particular, tested with 9999 jobs, which seems to be the maximum amount of jobs that Slurm can handle in queue for a single compute node.
**Current Limitation**
Unit tests have been implemented, but skipped, because they require the refactoring of the logging packages to prevent test failures, which is a more invasive change we want to decouple from this bugfix. This seems unreasonable, but actually caused by the fact that PCUI logging utilities clashes with the logging library of Python, disturbing pytest.
By …
> [JobInfo] Fix the retrieval of job info by making the SSM command to store the outputs on CloudWatch logs to prevent truncation. 

- frontend/package-lock.json
- frontend/package.json
- requirements.in
- requirements.txt
1. Upgrade axios to version 1.8.2 (from 1.7.8).
1.  Upgrade cryptography to version 44.0.1 (from 43.0.1).
1.  Upgrade jinja to version 3.1.6 (from 3.1.5).
1. Upgrade nextjs to version 14.2.25 (from 14.2.21).
Deployed PCUI, login, logout, navigated cluster and images pages, create and deleted a cluster.
> [Dependencies] Upgraded nextjs, axios, cryptography and jinja2

- infrastructure/custom-domain/custom-domain.yaml
Add 1-click template to deploy resources for custom domain.
Used the template to deploy custom domain for both PCUI App and Cognito.
Then tested the created certificates with a PCUI deployment using custom domains.
> [Examples] Add 1-click template to deploy resources for custom domain.

- infrastructure/parallelcluster-ui.yaml
Make CloudFormation return a more clear error when the parameter Version is not specified.
Without this change CloudFormation will return a more complex error message saying that `Template error: Fn::Select cannot select nonexistent value at index 1`
Manually verified  with:
1. empty value
2. incorrect value
3. correct value
> Make CloudFormation return a more clear error when the parameter Version is not specified.

- frontend/Dockerfile
Upgrade NodeJS from 18.20 to 22.14 in PCUI Docker container as NodeJs 18 will be EOL on 2025/04/30.
Nodejs 22 will be EOL 2027/04/30.
Deployment succeeded. Navigated the main pages.
> [Dependencies] Upgrade NodeJS from 18.20 to 22.14 in PCUI Docker container

- api/tests/exceptions/test_exception_handlers.py
- api/tests/validation/test_api_custom_validators.py
- api/validation/__init__.py
- api/validation/schemas.py
- api/validation/validators.py
Mitigate the risk of path traversal attacks by adding a request validator that rejects requests containing a 'path' argument matching the unsafe path traversal pattern.
This mitigation, together with https://github.com/aws/aws-parallelcluster-ui/pull/422, provides a full mitigation of the path traversal attack.
1. Validator is covered by unit tests
2. PCUI is working as expected: login/logout, list clusters, create cluster, delete cluster, list images
3. The legit proxy request (the same form used by PCUI frontend) succeeds, example:
* https://[PCUI_URL]/pcui/api?path=/v3/images/official  
5. Path traversal gets rejected, regardless it points to the legitimate or illegitimate stage. Examples:
* (legitimate stage) https://hu0moxausi.execute-api.us-east-1.amazonaws.com/pcui/api?path=/../prod …
> [Security] Mitigate the risk of path traversal attacks through a request validator
