- infrastructure/environments/demo-cfn-update-args.yaml
> Update demo env to PC 3.5.0

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Storage.tsx
Adjust the layout of properties common to all storage types.
> Storage layout shared properties

- scripts/build_and_release_image.sh
This PR introduces two new optional parameters to allow a technician to specify different ecr region to perform the login at, and a different public ecr endpoint to push the lambda image to.
- manually
> Added parametrization of ecr region and endpoint parameters in `build_and_release` script

- infrastructure/parallelcluster-ui.yaml
Removed shortversion mapping and its usages
- manually deployed the stack in my personal account
> Removed shortversion mapping and its usages

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Components.tsx
- frontend/src/old-pages/Configure/Storage.tsx
- add a `CheckboxWithInfoPanel` component to show a checkbox with an info link aside
- adjust the EFS settings layout with the help of the `CheckboxWithInfoPanel` component
> Update EFS settings layout

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Storage.tsx
> Adjust FSx settings layout

- frontend/src/old-pages/Configure/HeadNode.tsx
> Fix SSM help panel rendering

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Storage.tsx
> Adjust EBS settings layout

- frontend/src/old-pages/Configure/Configure.tsx
- Validated with a cluster dry-run and a simple config
> Move Queues before Storage

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/MultiUser.tsx
- frontend/src/old-pages/Configure/__tests__/MultiUser.test.tsx
This PR aligns the generate SSH keys checkbox with other checkboxes, for UI consistency.
It also fixes an issue with the default value not being propagated to the final YAML config.
- use `CheckboxWithHelpPanel` in `MultiUser`
- add test for the default value initialization
- move the `Checkbox` description inside the `HelpPanel`, to increase consistency with other checkboxes in the app
- remove immediate validation upon touching the form, causing the validation errors showing up before the form is submitted 
- manually
- unit test
By submitting this pull request, I confirm that …
> Fix initialization issue of the Generate SSH Keys checkbox in MultiUser

- api/PclusterApiHandler.py
Some AWS Regions have C7 instances deployed. This change adds support for those.
> Add support for C7 family instances.

- frontend/locales/en/strings.json
- frontend/src/old-pages/Clusters/Actions.tsx
Added button group for the following cluster actions: view filesystem, edit cluster and delete cluster.
- grouped three cluster actions (view filesystem, edit and delete cluster)
- made only one of the start stop buttons appear at a time
- manually
- unit tests
- e2e in local
> Added clusters actions in button group

- decisions/20230310-scope-down-e2e-tests.md
> Add ADR on e2e scope

- infrastructure/environments/demo-cfn-update-args.yaml
Avoid pulling images during updates from the old public ECR.
> Update demo environment CFN request to point to the new ECR registry

- frontend/src/old-pages/Clusters/Actions.tsx
Disable Actions dropdown if no actions inside of it is enabled.
> Disable Actions dropdown if no actions inside of it is enabled

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Components.tsx
- frontend/src/old-pages/Configure/HeadNode.tsx
> Move IAM additional policies to the Security container

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/HeadNode.tsx
> Add title to head node instance container

- frontend/locales/en/strings.json
- frontend/src/old-pages/Configure/Queues/Queues.tsx
> Align queues advanced options layout

- e2e/specs/wizard.spec.ts
- e2e/specs/wizard.template.spec.ts
> Fix e2e after head node changes

- frontend/src/old-pages/Logs/index.tsx
This PR adds the main breadcrumb item to Cluster Logs page, so to be consistent with all the other pages of the app
- add main breadcrumb item
- manually, by clicking on each component of the breadcrumb
> Add main breadcrumb item to the Cluster Logs page

- frontend/locales/en/strings.json
- frontend/src/old-pages/Logs/index.tsx
This PR updates the text of the help panel of the Cluster Logs page
- manually, see screenshot
> Update HelpPanel text of Cluster Logs page

- e2e/test-utils/logs.ts
> Fix failing e2e of logs page

- decisions/20230324-avoid-overriding-customer-ssm-sessionmanagerrunshell-removing-ssmsessionprofile-cfnyaml.md
ADR about the removal of the cloudformation substack SSMSessionProfile-cfn.yaml
> Removal of the cloudformation substack SSMSessionProfile-cfn.yaml

- frontend/locales/en/strings.json
- frontend/src/old-pages/Clusters/Actions.tsx
- frontend/src/old-pages/Clusters/Filesystems.tsx
- frontend/src/old-pages/Clusters/Scheduling.tsx
- frontend/src/old-pages/Configure/Cluster.tsx
- frontend/src/old-pages/Configure/Components.tsx
- frontend/src/old-pages/Configure/Queues/MultiInstanceComputeResource.tsx
- frontend/src/old-pages/Configure/Queues/Queues.test.tsx
- frontend/src/old-pages/Configure/Queues/SingleInstanceComputeResource.tsx
- frontend/src/old-pages/Users/Users.tsx
See Commits tab.
- dry run after selecting every affected property
> Copy changes and fixes

- infrastructure/parallelcluster-ui-cognito.yaml
Improve layout of the email to avoid copy/paste mistakes by users.
See image attached (the password is not valid)
- manually
> Improve layout of the email to avoid copy/paste mistakes by users

- frontend/src/old-pages/Configure/__tests__/storage.test.tsx
> Improve storage tests using jest.each

- frontend/src/components/useLoadingState.tsx
Improved loading spinner styling which now has a margin from the top of the window.
- manually
#132 
> Improved loading spinner styling

- e2e/test-utils/wizard.ts
> Fix e2e failing to select the region during the wizard

- infrastructure/parallelcluster-ui.yaml
> Bump PCUI version to 2023.04

- frontend/locales/en/strings.json
> HeadNode help panel copy nitpick

- frontend/locales/en/strings.json
- frontend/src/old-pages/Clusters/Clusters.tsx
- frontend/src/old-pages/Configure/HeadNode.tsx
- frontend/src/old-pages/Configure/Queues/SlurmMemorySettings.tsx
- frontend/src/old-pages/Configure/SlurmSettings/SlurmAccountingForm.tsx
- frontend/src/old-pages/Configure/Storage.tsx
* Fixed copy and added missing links in help panels
* Manually inspected affected pages
> Fix copy and add missing links in help panels

- .github/pull_request_template.md
- .github/release.yml
This PR adds an item to the PR checklist to make sure devs remember to link a solved GH issue when one exists
This PR also improved the current changelog template.
> Improved release changelog template + added checklist item for solved GH issues

- frontend/locales/en/strings.json
> Add missing period at the end of the sentence

- frontend/locales/en/strings.json
- frontend/src/old-pages/Users/AddUserModal.tsx
- frontend/src/old-pages/Users/Users.tsx
- frontend/src/old-pages/Users/__tests__/AddUserModal.test.tsx
- frontend/src/old-pages/Users/__tests__/userValidate.test.ts
* Make the user creation flow compliant with Cloudscape by using a dedicated modal
* Fixed user email regex which allowed emails without domain such as `test@domain`
* Unit tests
* Manually tested on local environment
* Verified that if not valid email is entered the formfield displays an error
* Verified that with a valid email user creation is successful and modal is dismissed 
* Verified that with an existing email modal is dismissed and error flashbar is displayed
* https://cloudscape.design/components/modal/
By submitting this pull request, I confirm that you can use, …
> Make the user creation flow compliant with Cloudscape by using a dedicated modal

- requirements.txt
Pin Werkzeug to version 2.2.2 to avoid surprises in our CI build.
> Pin Werkzeug to version 2.2.2

- infrastructure/parallelcluster-ui.yaml
Keep the number of managed policies under or equal to 10 for lambda role
> Keep the number of managed policies under or equal to 10 for lambda role

- DEVELOPMENT.md
- requirements.in
- requirements.txt
This PR introduces the use of pip-tools and locks all dependencies versions for the backend.
- manually
- unit tests
> Lock python dependencies by adopoting `pip-tools`

- e2e/specs/users.spec.ts
- e2e/test-utils/users.ts
Add end-to-end tests for `Users` page. 
Use cases covered:
* Add user with valid email
* Add user with invalid email
* Delete user
* Delete logged user
* e2e tests
> Add e2e tests for Users page

- frontend/resources/attributions/npm-python-attributions.txt
- resources/attributions/docker-attributions.txt
> Update attributions files

- infrastructure/parallelcluster-ui.yaml
> Bump PCUI version

- requirements.in
- requirements.txt
Bump `requests` from **2.28.1** to **2.31.0** to solve https://github.com/aws/aws-parallelcluster-ui/security/dependabot/9.
* Bumped requests version in `requirements.in`
* Ran `pip-compile` to generate `requirements.txt`
* Installed deps in virtualenv through `pip install -r requirements.txt`
* Successfully started and navigated through the portal, creating and deleting a cluster
* https://github.com/aws/aws-parallelcluster-ui/security/dependabot/9
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
> Bump requests from 2.28.1 to 2.31.0

- infrastructure/parallelcluster-ui.yaml
> Update PCUI version to 2023.06.0

- infrastructure/parallelcluster-ui-cognito.yaml
- infrastructure/parallelcluster-ui.yaml
This reverts commit 6aaed036adae5ab1facab86fb9144207c2c7de03.
Reason: to merge any changes reliant on PC API, we need to do the following in order:
1. Release a new version of PC API
2. Bump version in PC UI
3. Merge the changes
For this specific commit, we need to
1. Wait for ParallelCluster 3.8.0 release, because the PC API related change is in 3.8.0 https://github.com/aws/aws-parallelcluster/pull/5640
2. Bump version in PC UI to 3.8.0
3. Merge the changes
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
> Revert "[PCUI]Add PermissionBoundary for every IAM role and prefix for every IAM role and policy. (#255)"

- infrastructure/parallelcluster-ui.yaml
Bump PCUI version to 2023.10.0.
> [Versioning] Bump PCUI version to 2023.10.0.

- DEVELOPMENT.md
- infrastructure/environments/demo-cfn-update-args.yaml
- infrastructure/parallelcluster-ui.yaml
Bump pcluster version to 3.7.2
Version bumped in: 
* CloudFormation template
* scripts and docs used for the internal dev process.
[ONGOING] Deployed and tested in personal account
> [Versioning] Bump pcluster version to 3.7.2.

- infrastructure/update-environment-infra.sh
- scripts/README.md
- scripts/build_and_release_image.sh
Minor changes to script and documentation related to the local dev process.
1. Added log lines in `build_and_release_image.sh`
2. Added instructions about how to build and publish a PCUI image in personal account.
3. 3. Specify AWS region in `update-environment-infra.sh` so that it can be used in whatever region, not only the one assumed for the demo environment (eu-west-1).
Steps have been manually tested.
> [Ops] Minor changes to script and documentation related to the local dev process

- requirements.in
- requirements.txt
Upgrade urllib3 to 1.26.18.
1. Deployed PCUI on personal account, logged in and listed clusters
> [Dependencies] Upgrade urllib3 to 1.26.18.

- infrastructure/environments/demo-cfn-create-args.yaml
- infrastructure/environments/demo-cfn-update-args.yaml
- scripts/setup-env.sh
1. Add cfn file to create demo environment + minor change to cfn file to update it.
2. Make `setup-env.sh` create files with the right extensions (yaml) and emit more explicative logs.
1. Used `setup.env.sh` to create a brand new env (it uses the demo env files as starting point)
3. Used `deploy.sh` to deploy such new env
> [Environment] Add/fix env files for demo env + fixes to the setup-env tool

- frontend/package-lock.json
- frontend/package.json
- frontend/resources/attributions/npm-python-attributions.txt
- Bump axios to 1.6.7 from 1.6.4 since there were bug fixes
npm test, deployed, created/deleted cluster
> [Dependencies] Bump axios to 1.6.7

- DEVELOPMENT.md
- infrastructure/environments/demo-cfn-update-args.yaml
- infrastructure/parallelcluster-ui.yaml
Bump pcluster version to 3.9.0
> [Dependencies] Bump pcluster version to 3.9.0

- infrastructure/parallelcluster-ui.yaml
Bump PCUI version to 2024.03.0
> [Versioning] Bump PCUI version to 2024.03.0

- infrastructure/parallelcluster-ui.yaml
> Bump PCUI to 2024.04.0 for pcluster 3.9.1 emergency release

- infrastructure/environments/demo-cfn-create-args.yaml
- infrastructure/environments/demo-cfn-update-args.yaml
- Update demo env config files to 3.9.1
> Update demo env files to 3.9.1

- infrastructure/parallelcluster-ui.yaml
Bump PCUI version to 2024.05.0.
Deployed to personal account.
> [Versioning] Bump PCUI version to 2024.05.0.

- infrastructure/parallelcluster-ui.yaml
> [Versioning] Bump PCUI version to 2024.07.0

- infrastructure/environments/demo-cfn-create-args.yaml
- infrastructure/environments/demo-cfn-update-args.yaml
- infrastructure/parallelcluster-ui.yaml
> [Versioning] Bump PC CLI version to 3.10.0

- infrastructure/parallelcluster-ui.yaml
Improve description of parameter ImageBuilderSubnetId.
> [Template] Improve description of parameter ImageBuilderSubnetId.

- infrastructure/parallelcluster-ui.yaml
Version bumped from 2024.07.0 to 2024.07.1.
No need to test the bump.
> [Versioning] Version bumped to 2024.07.1.

- infrastructure/environments/demo-cfn-create-args.yaml
- infrastructure/environments/demo-cfn-update-args.yaml
- infrastructure/parallelcluster-ui.yaml
Bump PC version to 3.10.1.
1. Deployed PCUI in personal env
2. Created a 3.10.1 cluster
3. Deleted the same cluster
> [Versioning] Bump PC version to 3.10.1.

- frontend/package-lock.json
- frontend/package.json
- requirements.in
- requirements.txt
> Revert dependabot update commits, last 6

- infrastructure/environments/demo-cfn-create-args.yaml
- infrastructure/environments/demo-cfn-update-args.yaml
- infrastructure/parallelcluster-ui.yaml
Fix support for custom domain.
In particular:
1. added a new optional parameter 'CustomDomain' to the PCUI stack to specify the custom domain name. If omitted the default domain name generated by API Gateway is used (current behaviour)
2. when using a custom domain, the APIG stage name is set to `prod` rather than `pcui`; otherwise `pcui` is used (current behaviour).
3. when using a custom domain, the Lambda envar `API_GATEWAY_BASE_PATH` is set to `pcui`; otherwise it is omitted (current behaviour)
4. when using a custom domain, the Lambda envar SITE_URL is set to `https://${CustomDomain}/prod`; otherwise it is set to `https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/pcui` (Current behaviour)
5. Added `CustomDomain` (intentionally commented out) to the env files for the demo …
> Fix support for custom domain

- frontend/package-lock.json
To address CVE-2024-21538
Upgrade cross-spawn to 7.0.6
> [PCUI] Upgrade cross-spawn to 7.0.6 to address CVE

- frontend/package-lock.json
- frontend/package.json
[Dependency] Upgrade Next.js to 14.2.21
Deployed in personal account and created a basic cluster.
> [Dependency] Upgrade Next.js to 14.2.21

- infrastructure/parallelcluster-ui.yaml
Bump PCUI version to 2025.04.0.
> [Versioning] Bump PCUI version to 2025.04.0.
